# -*- coding: utf-8 -*-
"""create_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155JU4spkYAKQhMRoh8f4sgapuuUpmzD2
"""

import sqlite3

conn = sqlite3.connect("recommendation.db")
cursor = conn.cursor()

# Create users table
cursor.execute('''
CREATE TABLE IF NOT EXISTS users (
    userID TEXT PRIMARY KEY,
    previousPurchases TEXT
)
''')

# Create tools table
cursor.execute('''
CREATE TABLE IF NOT EXISTS tools (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT,
    Title_URL TEXT,
    Image TEXT
)
''')

# Sample tool data
tools_data = [
    ("Scalpel", "https://example.com/scalpel", "https://example.com/images/scalpel.jpg"),
    ("Forceps", "https://example.com/forceps", "https://example.com/images/forceps.jpg"),
    ("Retractor", "https://example.com/retractor", "https://example.com/images/retractor.jpg"),
    ("Surgical Scissors", "https://example.com/scissors", "https://example.com/images/scissors.jpg"),
    ("Clamp", "https://example.com/clamp", "https://example.com/images/clamp.jpg")
]

cursor.executemany("INSERT INTO tools (Title, Title_URL, Image) VALUES (?, ?, ?)", tools_data)

# Optional: Add some initial users
users_data = [
    ("user1", "Scalpel|Clamp"),
    ("user2", "Forceps|Scalpel"),
    ("user3", "Retractor|Surgical Scissors"),
]

cursor.executemany("INSERT INTO users (userID, previousPurchases) VALUES (?, ?)", users_data)

conn.commit()
conn.close()